name: Deploy React Frontend

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/deploy-frontend.yml'
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build React
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Upload React build to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "client/build/*"
          target: "/home/${{ secrets.VPS_USERNAME }}/apps/my-project/client/build"

      - name: Reload NGINX
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: sudo systemctl reload nginx
