name: Deploy Express Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install backend deps
        working-directory: ./backend
        run: |
          npm install

      - name: Upload backend to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "backend/*"
          target: "/home/${{ secrets.VPS_USERNAME }}/apps/blindblind/backend"

      - name: 🔁 Restart PM2 backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            npm install -g pm2
            cd /home/${{ secrets.VPS_USERNAME }}/apps/blindblind/backend
            pm2 restart blindblind
